apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: web-bff-pubsub
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
    - name: connectionString
      value: 'amqp://admin:admin123@127.0.0.1:5672'
    - name: protocol
      value: amqp
    - name: hostname
      value: '127.0.0.1:5672'
    - name: consumerID
      value: web-bff
